### ISSUE TITLE
XML 中无法输入多行文本

### ISSUE THREAD

**Issue by HarrisonXi** [alibaba/virtualview_tools#7]
<VText
                layoutWidth="50"
                layoutHeight="50"
                background="#0000FF"
                textSize="12"
                layoutGravity="v_center|h_center"
                gravity="h_center"
                lines="2"
                text="1\nheight = 100" />

类似以上 XML 无法生效，文本 text 的值为 "1"，转义符及后续内容被截断。

尝试使用 `&#x0020;` 也无效。

**Comment by longerian** [comment]
换行符应该用 `&#x0A;` 代替 @HarrisonXi
